title: CS 533 Fall 2021
author: Michael D. Ekstrand
copyright: '2021'
# logo: logo.png

# bibtex_bibfiles:
  # - references.bib

repository:
  url: https://github.com/mdekstrand/cs533-web
  branch: main

parse:
  myst_heading_anchors: 2
  myst_enable_extensions:
    - colon_fence
    - deflist
    - dollarmath
    - linkify
    - substitution
  myst_substitutions:
    moverview: 🧐
    mcal: 📅
    mvideo: 🎥
    mbook: 📖
    mclass: 👨‍🏫
    mnotebook: 📝
    massignment: 📩
    mtask: ✅
    mquiz: 🚩
    mdownload: 🌠

execute:
  execute_notebooks: 'off'
  exclude_patterns:
  - assignments/*/*.ipynb
  - resources/tutorials/*.ipynb

html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  favicon: logo.png
  comments:
    utterances:
      repo: mdekstrand/cs533-web

launch_buttons:
  binderhub_url: ''

sphinx:
  local_extensions:
    admonitions: extensions
    media: extensions
    cleanups: extensions
  config:
    primary_domain: res
    mathjax_config:
      TeX:
        Macros:
          E: "\\mathrm{E}"
          F: "\\mathcal{F}"
          P: "P"
          Cov: "\\mathrm{Cov}"
          Var: "\\mathrm{Var}"
          log: "\\operatorname{log}"
          Odds: "\\operatorname{Odds}"
          OR: "\\operatorname{OR}"
          IND: "\\mathbb{I}"
          Reals: "\\mathbb{R}"
    intersphinx_mapping:
      python: [https://docs.python.org/3, null]
      numpy: [https://numpy.org/doc/stable/, null]
      scipy: [https://docs.scipy.org/doc/scipy/reference/, null]
      seaborn: [https://seaborn.pydata.org/, null]
      matplotlib: [https://matplotlib.org/, null]
      sklearn: [https://scikit-learn.org/stable/, null]
